name: Lambda Deploy - nisroom-api-dev
on:
  push:
    branches:
      - migration
    paths:
      - "**/*.js"
      - "**/*.json"
      - "**/deploy_nisroom_api_dev.yml"
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install --production
      - run: zip -r function.zip .
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: |
          aws lambda update-function-code --function-name nisroom-api-dev --zip-file fileb://function.zip
