name: Deploy - nisroomAPI
on:
  push:
    branches:
      - main
    paths:
      - "nisroomAPI/**"
jobs:
  AWS_Lambda_Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install --production && zip -r function.zip .
        working-directory: ./nisroomAPI
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: aws lambda update-function-code --function-name nisroomAPI --zip-file fileb://function.zip
        working-directory: ./nisroomAPI
