name: Lambda Deploy - patchSchedule
on:
  push:
    branches:
      - main
    paths:
      - "src/patchSchedule/**"
jobs:
  AWS_Lambda_Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      # - run: npm install --production
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: |
          zip -j function.zip ./src/patchSchedule/index.js
          aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_PATCHSCHEDULE }} --zip-file fileb://function.zip
